# This is a basic workflow that is manually triggered

name: Action Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, every minute of 0
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commit_message:
        description: "Commit message used while committing to the repo"
        default: "Updated with the latest blog posts"
        required: false
      committer_username:
        description: "Username used while committing to the repo"
        default: "web-scrapping-bot"
        required: false
      committer_email:
        description: "Email id used while committing to the repo"
        default: "scrapping-bot@example.com"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Update Data
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install lxml
        run: pip install lxml
      - name: Install htmlmin
        run: pip install htmlmin
      - name: Run main.py
        run: python main.py
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9