# This is a basic workflow that is manually triggered

name: Action Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commit_message:
        description: "Commit message used while committing to the repo"
        default: "Updated with the latest blog posts"
        required: false
      committer_username:
        description: "Username used while committing to the repo"
        default: "blog-post-bot"
        required: false
      committer_email:
        description: "Email id used while committing to the repo"
        default: "blog-post-bot@example.com"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v3
      - run: python main.py